export const LOGIN_SUBMITTED = 'LOGIN_SUBMITTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_CHANGE_PASSWORD_REQUIRED = 'LOGIN_CHANGE_PASSWORD_REQUIRED';
export const LOGIN_CHANGE_PASSWORD_SUBMITTED = 'LOGIN_CHANGE_PASSWORD_SUBMITTED';
export const LOGIN_CHANGE_PASSWORD_FAILED = 'LOGIN_CHANGE_PASSWORD_FAILED';

export const PASSWORD_RESET_STARTED = 'PASSWORD_RESET_STARTED';
export const PASSWORD_RESET_CODE_SUBMITTED = 'PASSWORD_RESET_CODE_SUBMITTED';
export const PASSWORD_RESET_CODE_VALID = 'PASSWORD_RESET_CODE_VALID';
export const PASSWORD_RESET_CODE_INVALID = 'PASSWORD_RESET_CODE_INVALID';
export const PASSWORD_RESET_PASSWORD_SUBMITTED = 'PASSWORD_RESET_PASSWORD_SUBMITTED';
export const PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE';
export const PASSWORD_RESET_PASSWORD_INVALID = 'PASSWORD_RESET_PASSWORD_INVALID';

export const SESSION_ESTABLISHED = 'SESSION_ESTABLISHED';
